/*
================================================================================
  Daily Tasks Tracking System (TTS)
  File: schema.sql
  Description: Database schema DDL — Tables, Sequences, Indexes, Constraints
  APEX Version: 24.2.17
  Author: TTS Development Team
  Created: 2026-07-07
================================================================================
  EXECUTION ORDER: Run this file FIRST before any other scripts.
  NOTE: This script will DROP existing objects before re-creating them.
================================================================================
*/

SET SERVEROUTPUT ON;
SET DEFINE OFF;

PROMPT ============================================================
PROMPT  TTS Schema Installation — Starting...
PROMPT ============================================================

-- ============================================================
-- SECTION 1: DROP EXISTING OBJECTS (reverse dependency order)
-- ============================================================
PROMPT Dropping existing objects...

BEGIN
    FOR rec IN (
        SELECT table_name FROM user_tables 
        WHERE table_name IN (
            'TTS_TASK_TAGS','TTS_TAGS','TTS_NOTIFICATIONS','TTS_TASK_HISTORY',
            'TTS_ATTACHMENTS','TTS_COMMENTS','TTS_DAILY_LOG','TTS_TASKS',
            'TTS_SYSTEMS','TTS_USERS','TTS_DEPARTMENTS','TTS_LOOKUPS'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS PURGE';
        DBMS_OUTPUT.PUT_LINE('  Dropped table: ' || rec.table_name);
    END LOOP;
END;
/

BEGIN
    FOR rec IN (
        SELECT sequence_name FROM user_sequences 
        WHERE sequence_name = 'TTS_TASK_NUMBER_SEQ'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || rec.sequence_name;
        DBMS_OUTPUT.PUT_LINE('  Dropped sequence: ' || rec.sequence_name);
    END LOOP;
END;
/

-- ============================================================
-- SECTION 2: CREATE TABLES
-- ============================================================

-- ------------------------------------------------------------
-- 2.1  tts_lookups — Flexible reference/lookup data
-- ------------------------------------------------------------
PROMPT Creating table: tts_lookups...

CREATE TABLE tts_lookups (
    lookup_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lookup_type     VARCHAR2(50)  NOT NULL,
    lookup_code     VARCHAR2(50)  NOT NULL,
    display_name    VARCHAR2(100) NOT NULL,
    display_name_ar VARCHAR2(100),
    display_order   NUMBER DEFAULT 0,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT chk_lookups_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT uk_lookups UNIQUE (lookup_type, lookup_code)
);

COMMENT ON TABLE  tts_lookups IS 'Centralized lookup/reference values for all dropdowns and statuses';
COMMENT ON COLUMN tts_lookups.lookup_type IS 'Category: TASK_STATUS, PRIORITY, APPROVAL_STATUS, NOTIFICATION_TYPE';
COMMENT ON COLUMN tts_lookups.display_name_ar IS 'Arabic display label for bilingual support';

-- ------------------------------------------------------------
-- 2.2  tts_departments — Organizational departments
-- ------------------------------------------------------------
PROMPT Creating table: tts_departments...

CREATE TABLE tts_departments (
    dept_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name    VARCHAR2(100) UNIQUE NOT NULL,
    dept_head_id NUMBER,
    is_active    CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_dept_active CHECK (is_active IN ('Y', 'N'))
);

COMMENT ON TABLE tts_departments IS 'Organizational departments for grouping users';

-- ------------------------------------------------------------
-- 2.3  tts_users — System users (employees, managers, admins)
-- ------------------------------------------------------------
PROMPT Creating table: tts_users...

CREATE TABLE tts_users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50)  UNIQUE NOT NULL,
    password_hash VARCHAR2(256) NOT NULL,
    password_salt VARCHAR2(128) NOT NULL,
    email         VARCHAR2(100) UNIQUE NOT NULL,
    full_name     VARCHAR2(150) NOT NULL,
    role          VARCHAR2(20)  NOT NULL,
    dept_id       NUMBER,
    manager_id    NUMBER,
    is_active     CHAR(1) DEFAULT 'Y' NOT NULL,
    last_login    TIMESTAMP,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_users_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT fk_users_dept    FOREIGN KEY (dept_id)    REFERENCES tts_departments(dept_id),
    CONSTRAINT fk_users_manager FOREIGN KEY (manager_id) REFERENCES tts_users(user_id)
);

COMMENT ON TABLE  tts_users IS 'All system users with authentication and role information';
COMMENT ON COLUMN tts_users.role IS 'User role: ADMIN, MANAGER, EMPLOYEE';
COMMENT ON COLUMN tts_users.password_salt IS 'Random salt used with SHA-256 hashing for password security';

-- Add the deferred FK from departments back to users
ALTER TABLE tts_departments ADD CONSTRAINT fk_dept_head 
    FOREIGN KEY (dept_head_id) REFERENCES tts_users(user_id);

-- ------------------------------------------------------------
-- 2.4  tts_systems — Business systems/applications
-- ------------------------------------------------------------
PROMPT Creating table: tts_systems...

CREATE TABLE tts_systems (
    system_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_name  VARCHAR2(100) UNIQUE NOT NULL,
    description  VARCHAR2(4000),
    is_active    CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_systems_active CHECK (is_active IN ('Y', 'N'))
);

COMMENT ON TABLE tts_systems IS 'Business systems/applications that tasks are associated with';

-- ------------------------------------------------------------
-- 2.5  tts_tasks — Core tasks table
-- ------------------------------------------------------------
PROMPT Creating table: tts_tasks...

CREATE TABLE tts_tasks (
    task_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_number      VARCHAR2(20)  UNIQUE NOT NULL,
    title            VARCHAR2(250) NOT NULL,
    description      CLOB,
    system_id        NUMBER NOT NULL,
    assigned_to      NUMBER NOT NULL,
    created_by       NUMBER NOT NULL,
    status           VARCHAR2(20) DEFAULT 'CREATED'         NOT NULL,
    priority         VARCHAR2(20) DEFAULT 'MEDIUM'          NOT NULL,
    start_date       DATE NOT NULL,
    due_date         DATE NOT NULL,
    estimated_hours  NUMBER(6,2) NOT NULL,
    actual_hours     NUMBER(6,2) DEFAULT 0,
    completion_date  DATE,
    approval_status  VARCHAR2(20) DEFAULT 'NOT_SUBMITTED'   NOT NULL,
    approved_by      NUMBER,
    approval_notes   VARCHAR2(4000),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_tasks_system   FOREIGN KEY (system_id)   REFERENCES tts_systems(system_id),
    CONSTRAINT fk_tasks_assigned FOREIGN KEY (assigned_to) REFERENCES tts_users(user_id),
    CONSTRAINT fk_tasks_creator  FOREIGN KEY (created_by)  REFERENCES tts_users(user_id),
    CONSTRAINT fk_tasks_approver FOREIGN KEY (approved_by) REFERENCES tts_users(user_id),
    CONSTRAINT chk_tasks_dates     CHECK (due_date >= start_date),
    CONSTRAINT chk_tasks_est_hours CHECK (estimated_hours >= 0),
    CONSTRAINT chk_tasks_act_hours CHECK (actual_hours >= 0)
);

COMMENT ON TABLE  tts_tasks IS 'Core tasks table — tracks all daily tasks with lifecycle management';
COMMENT ON COLUMN tts_tasks.task_number IS 'Human-readable auto-generated ID: TSK-000001';
COMMENT ON COLUMN tts_tasks.approval_status IS 'NOT_SUBMITTED (default), PENDING, APPROVED, REJECTED';
COMMENT ON COLUMN tts_tasks.approval_notes IS 'Manager notes when approving or rejecting a task';

-- ------------------------------------------------------------
-- 2.6  tts_daily_log — Daily time tracking per task
-- ------------------------------------------------------------
PROMPT Creating table: tts_daily_log...

CREATE TABLE tts_daily_log (
    log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      NUMBER NOT NULL,
    user_id      NUMBER NOT NULL,
    log_date     DATE   NOT NULL,
    hours_spent  NUMBER(4,2) NOT NULL,
    notes        VARCHAR2(4000),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_log_task  FOREIGN KEY (task_id) REFERENCES tts_tasks(task_id) ON DELETE CASCADE,
    CONSTRAINT fk_log_user  FOREIGN KEY (user_id) REFERENCES tts_users(user_id),
    CONSTRAINT chk_log_hours CHECK (hours_spent > 0 AND hours_spent <= 24),
    CONSTRAINT uk_daily_log  UNIQUE (task_id, user_id, log_date)
);

COMMENT ON TABLE  tts_daily_log IS 'Daily time entries — each row represents hours worked on a task for a specific day';
COMMENT ON COLUMN tts_daily_log.hours_spent IS 'Hours worked (0-24), auto-summed into tts_tasks.actual_hours';

-- ------------------------------------------------------------
-- 2.7  tts_comments — Task discussion/comments
-- ------------------------------------------------------------
PROMPT Creating table: tts_comments...

CREATE TABLE tts_comments (
    comment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      NUMBER NOT NULL,
    user_id      NUMBER NOT NULL,
    comment_text CLOB   NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES tts_tasks(task_id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES tts_users(user_id)
);

COMMENT ON TABLE tts_comments IS 'Task comments/discussion thread';

-- ------------------------------------------------------------
-- 2.8  tts_attachments — File attachments on tasks
-- ------------------------------------------------------------
PROMPT Creating table: tts_attachments...

CREATE TABLE tts_attachments (
    attachment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       NUMBER        NOT NULL,
    file_name     VARCHAR2(255) NOT NULL,
    file_mimetype VARCHAR2(100) NOT NULL,
    file_blob     BLOB          NOT NULL,
    file_charset  VARCHAR2(100),
    uploaded_by   NUMBER NOT NULL,
    uploaded_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_attach_task FOREIGN KEY (task_id)     REFERENCES tts_tasks(task_id) ON DELETE CASCADE,
    CONSTRAINT fk_attach_user FOREIGN KEY (uploaded_by) REFERENCES tts_users(user_id)
);

COMMENT ON TABLE tts_attachments IS 'File attachments stored as BLOBs, linked to tasks';

-- ------------------------------------------------------------
-- 2.9  tts_task_history — Audit trail for task changes
-- ------------------------------------------------------------
PROMPT Creating table: tts_task_history...

CREATE TABLE tts_task_history (
    history_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      NUMBER NOT NULL,
    changed_by   NUMBER NOT NULL,
    changed_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    change_type  VARCHAR2(50) NOT NULL,
    old_value    VARCHAR2(4000),
    new_value    VARCHAR2(4000),
    CONSTRAINT fk_hist_task FOREIGN KEY (task_id)    REFERENCES tts_tasks(task_id) ON DELETE CASCADE,
    CONSTRAINT fk_hist_user FOREIGN KEY (changed_by) REFERENCES tts_users(user_id)
);

COMMENT ON TABLE  tts_task_history IS 'Complete audit trail of all task changes';
COMMENT ON COLUMN tts_task_history.change_type IS 'Type of change: STATUS, ASSIGNMENT, PRIORITY, APPROVAL, CREATED';

-- ------------------------------------------------------------
-- 2.10 tts_notifications — In-app & email notifications
-- ------------------------------------------------------------
PROMPT Creating table: tts_notifications...

CREATE TABLE tts_notifications (
    notification_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER         NOT NULL,
    task_id           NUMBER,
    notification_type VARCHAR2(50)   NOT NULL,
    message           VARCHAR2(4000) NOT NULL,
    is_read           CHAR(1) DEFAULT 'N' NOT NULL,
    email_sent        CHAR(1) DEFAULT 'N' NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_notif_user  FOREIGN KEY (user_id) REFERENCES tts_users(user_id),
    CONSTRAINT fk_notif_task  FOREIGN KEY (task_id)  REFERENCES tts_tasks(task_id) ON DELETE SET NULL,
    CONSTRAINT chk_notif_read  CHECK (is_read    IN ('Y', 'N')),
    CONSTRAINT chk_notif_email CHECK (email_sent IN ('Y', 'N'))
);

COMMENT ON TABLE  tts_notifications IS 'In-app notifications with optional email delivery tracking';
COMMENT ON COLUMN tts_notifications.notification_type IS 'TASK_ASSIGNED, STATUS_CHANGED, APPROVAL_REQUIRED, APPROVAL_RESULT, COMMENT_ADDED, TASK_OVERDUE';

-- ------------------------------------------------------------
-- 2.11 tts_tags — Tag definitions
-- ------------------------------------------------------------
PROMPT Creating table: tts_tags...

CREATE TABLE tts_tags (
    tag_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR2(50) UNIQUE NOT NULL
);

COMMENT ON TABLE tts_tags IS 'Tag/label definitions for categorizing tasks';

-- ------------------------------------------------------------
-- 2.12 tts_task_tags — Many-to-many: Tasks <-> Tags
-- ------------------------------------------------------------
PROMPT Creating table: tts_task_tags...

CREATE TABLE tts_task_tags (
    task_id NUMBER NOT NULL,
    tag_id  NUMBER NOT NULL,
    CONSTRAINT pk_task_tags  PRIMARY KEY (task_id, tag_id),
    CONSTRAINT fk_ttags_task FOREIGN KEY (task_id) REFERENCES tts_tasks(task_id) ON DELETE CASCADE,
    CONSTRAINT fk_ttags_tag  FOREIGN KEY (tag_id)  REFERENCES tts_tags(tag_id)   ON DELETE CASCADE
);

COMMENT ON TABLE tts_task_tags IS 'Junction table linking tasks to tags (many-to-many)';

-- ============================================================
-- SECTION 3: SEQUENCE
-- ============================================================
PROMPT Creating sequence: tts_task_number_seq...

CREATE SEQUENCE tts_task_number_seq 
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE 
    NOCYCLE;

-- ============================================================
-- SECTION 4: PERFORMANCE INDEXES
-- ============================================================
PROMPT Creating performance indexes...

-- Users indexes
CREATE INDEX idx_users_manager    ON tts_users(manager_id);
CREATE INDEX idx_users_dept       ON tts_users(dept_id);
CREATE INDEX idx_users_role       ON tts_users(role);

-- Tasks indexes (most critical for query performance)
CREATE INDEX idx_tasks_assigned   ON tts_tasks(assigned_to);
CREATE INDEX idx_tasks_created_by ON tts_tasks(created_by);
CREATE INDEX idx_tasks_status     ON tts_tasks(status);
CREATE INDEX idx_tasks_system     ON tts_tasks(system_id);
CREATE INDEX idx_tasks_priority   ON tts_tasks(priority);
CREATE INDEX idx_tasks_dates      ON tts_tasks(start_date, due_date);
CREATE INDEX idx_tasks_approval   ON tts_tasks(approval_status);

-- Daily log indexes
CREATE INDEX idx_daily_log_task   ON tts_daily_log(task_id);
CREATE INDEX idx_daily_log_user   ON tts_daily_log(user_id);
CREATE INDEX idx_daily_log_date   ON tts_daily_log(log_date);

-- Comments indexes
CREATE INDEX idx_comments_task    ON tts_comments(task_id);

-- History indexes
CREATE INDEX idx_history_task     ON tts_task_history(task_id);

-- Notifications indexes
CREATE INDEX idx_notif_user       ON tts_notifications(user_id);
CREATE INDEX idx_notif_read       ON tts_notifications(user_id, is_read);

-- ============================================================
-- DONE
-- ============================================================
PROMPT ============================================================
PROMPT  TTS Schema Installation — COMPLETED SUCCESSFULLY
PROMPT  Tables created:  12
PROMPT  Sequences:       1
PROMPT  Indexes:         17
PROMPT ============================================================

